---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  listen: Restart systemd-resolved

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd.service
    state: restarted
  listen: Restart sssd